### ISSUE TITLE
Remove User Selection From New Product Form

### ISSUE THREAD

**Issue by daynewright** [TeamCharles/initial-site#107]
### Feature Description

Remove the user selection dropdown from the add product form and have it use the current selected logged in user.
### Recommended Actions

> Refer to the [project requirements](https://github.com/TeamCharles/bangazon-inc/blob/master/projects/INITIAL_BANGAZON_SITE.md#requirements) before filling out this section.

**Comment by Anulfo** [comment]
It was referenced on PR #111
