### ISSUE TITLE
Generate Layout

### ISSUE THREAD

**Issue by MattKraatz** [TeamCharles/initial-site#11]
### Feature Description

Create a Layout using Razor for customer-facing website. Layout to include header navigation, content body and footer.
### Requirement to Fulfill

> Refer to the [project requirements](https://github.com/TeamCharles/bangazon-inc/blob/master/projects/INITIAL_BANGAZON_SITE.md#requirements) before filling out this section.
1. In navigation bar, have a select element that allows you to pick which customer is active.
2. In the navigation bar, have an affordance that shows the current customer how many items are in their order.
3. If the user clicks on their order in the navigation bar, take them to the order detail view, which lists products, their prices, and current total for order.
4. In navigation bar, have a title/logo element.
5. If a user clicks on the title/logo element, take them to the product types view.

**Comment by matthamil** [comment]
Resolved with #58
