### ISSUE TITLE
View Bug Cart

### ISSUE THREAD

**Issue by garrett-vangilder** [TeamCharles/initial-site#115]
### Feature Description

Currently the app will only allow for Carson to view the app. 
### Recommended Actions

> Refer to the [project requirements](https://github.com/TeamCharles/bangazon-inc/blob/master/projects/INITIAL_BANGAZON_SITE.md#requirements) before filling out this section.
1. I would suggest implementing the Model View into the Cart Controller to allow for the cart controller to find the currently active user.

**Comment by matthamil** [comment]
This isn't a bug as Carson's account was intentionally hard coded into the Cart's Index method before the user log in worked.

**Comment by garrett-vangilder** [comment]
Yeah, I guess this is kind of mislabeled.
