### ISSUE TITLE
Create Product Detail View 

### ISSUE THREAD

**Issue by garrett-vangilder** [TeamCharles/initial-site#12]
### Feature Description

This user will access this view once they have clicked the hyperlinked product. It will include all information for the product as well as a button that will allow for users to add this product to an order.
### Requirement to Fulfill

> Refer to the [project requirements](https://github.com/TeamCharles/bangazon-inc/blob/master/projects/INITIAL_BANGAZON_SITE.md#requirements) before filling out this section.

https://github.com/TeamCharles/bangazon-inc/blob/master/projects/INITIAL_BANGAZON_SITE.md#generated-application

**Comment by MattKraatz** [comment]
Opening a new issue to change the view to reflect the model
