### ISSUE TITLE
Delete from Cart fails when multiple instances of the same product appears in the cart

### ISSUE THREAD

**Issue by MattKraatz** [TeamCharles/initial-site#124]
### Feature Description

If a user has multiple instances of the same product in their cart, when a user tries to delete that product, the program errors out.
### Recommended Actions

> Refer to the [project requirements](https://github.com/TeamCharles/bangazon-inc/blob/master/projects/INITIAL_BANGAZON_SITE.md#requirements) before filling out this section.
1.

**Comment by daynewright** [comment]
Fixed with pull request: #126
