### ISSUE TITLE
Use Product.IsActive instead of deleting the product

### ISSUE THREAD

**Issue by MattKraatz** [TeamCharles/initial-site#138]
### Feature Description

When we delete a product, it is eliminated from the database, instead of just changing the IsActive value to false.

### Recommended Actions
* Update Product/Delete function to change the value of IsActive and save to the DB
* Update all Razor templates to only show products that have an IsActive value of true
* Update Count function on Product Types and Product SubTypes to only count products that are Active

> Refer to the [project requirements](https://github.com/TeamCharles/bangazon-inc/blob/master/projects/INITIAL_BANGAZON_SITE.md#requirements) before filling out this section.
1. Remove IsActive from the Product model. Remove all references in the code.

**Comment by daynewright** [comment]
I think the idea of that feature originally was to never delete the products from the database so that when a user purchase a product it would still be able to be queried and show up on the order even if it was "deleted".  The product would simply be changed  to `IsActive = false`.

**Comment by MattKraatz** [comment]
Ah that makes sense. Might be worth updating the Product/Delete method.

**Comment by MattKraatz** [comment]
And the Product/Create method. It's currently setting that IsActive field to false.

**Comment by matthamil** [comment]
Resolved with #145
