### ISSUE TITLE
Multiple Line Item Delete

### ISSUE THREAD

**Issue by garrett-vangilder** [TeamCharles/initial-site#147]
### Feature Description

This is not a feature, but there is a bug. The bug is as follows: 
1.Add two of the same item. 
2. Go to your cart 
3. Delete one of the multiple items.
4. See Bug

### Recommended Actions
>Refer to the [project requirements](https://github.com/TeamCharles/bangazon-inc/blob/master/projects/INITIAL_BANGAZON_SITE.md#requirements) before filling out this section.

1. Go into the cart controller, where there is a delete lineitem method, fix it?

**Comment by matthamil** [comment]
Resolved with #149
