### ISSUE TITLE
Main Page/Product Types View User Story

### ISSUE THREAD

**Issue by NewEvolution** [TeamCharles/initial-site#17]
### Feature Description

Program flow for user interaction with the main page/product types view
### Requirement to Fulfill

**Given** the user is on any page of the application
**When** the user performs a gesture on the Bangazon icon/title
**Or**
**Given** the user is on the checkout completion page
**When** the user performs a gesture on the 'Continue Shopping' hyperlink
**Then** the customer will see an alphabetical list of all product types
**And** the list will display the name of the type
**And** the list will display the number of products in that type
**And** each name will be a hyperlink to display products of that type
### Notes

See #10 additionally

**Comment by MattKraatz** [comment]
Done, just need to redirect users back to the ProductTypes view on click of "Continue Shopping"
