### ISSUE TITLE
Mock Up

### ISSUE THREAD

**Issue by garrett-vangilder** [TeamCharles/initial-site#18]
### Feature Description

Mock-up
### Requirement to Fulfill

> This issue was suggested by Ryan.
### Notes

Mock Up will be created through Photoshop. This Mock up will include several different views. Those views include the following 

-Product List 
-Product Type
-Product Detail 
-Cart Detail
-Confirmation
-Account Creation 
-Payment Type Creation
-Product Creation
-Product List (seller)

**Comment by matthamil** [comment]
Resolved with branch `mockups`
