### ISSUE TITLE
Update Current Code 

### ISSUE THREAD

**Issue by garrett-vangilder** [TeamCharles/initial-site#26]
### Feature Description

This feature requires for us to update our current code.
### Requirement to Fulfill

> Refer to the [project requirements](https://github.com/TeamCharles/bangazon-inc/blob/master/projects/INITIAL_BANGAZON_SITE.md#requirements) before filling out this section.

Push up updated code to follow Steve's example.
### Notes

Matt will do this.

**Comment by matthamil** [comment]
Resolved
