### ISSUE TITLE
User Database Update

### ISSUE THREAD

**Issue by garrett-vangilder** [TeamCharles/initial-site#34]
### Feature Description

The database should be updated once the user has completed the new user form.
### Requirement to Fulfill

> Refer to the [project requirements](https://github.com/TeamCharles/bangazon-inc/blob/master/projects/INITIAL_BANGAZON_SITE.md#requirements) before filling out this section.

Once the user has completed the form and clicked the submit button, the following should happen: 
1. The database is updated to include the new user information.
2. The product types or products being sold view is shown.

**Comment by MattKraatz** [comment]
There is some progress on branch 35-user-controller
