### ISSUE TITLE
Update Product Detail View to reflect Product Model

### ISSUE THREAD

**Issue by MattKraatz** [TeamCharles/initial-site#65]
### Feature Description

This user will access this view once they have clicked the hyperlinked product. It will include all information for the product as well as a button that will allow for users to add this product to an order.
### Requirement to Fulfill

> Refer to the [project requirements](https://github.com/TeamCharles/bangazon-inc/blob/master/projects/INITIAL_BANGAZON_SITE.md#requirements) before filling out this section.
1. Product Detail view is broken. The field names need to be updated to reflect the model.

**Comment by daynewright** [comment]
@MattKraatz Can this issue be closed?  It looks like it is completed.

I opened #105 for updated styling with the detail view that still needs to be completed.
