### ISSUE TITLE
Update List.cshtml to reference Active User

### ISSUE THREAD

**Issue by MattKraatz** [TeamCharles/initial-site#73]
### Feature Description

Around line 19 currently is this expression `@if (item.UserId == 1)`. This needs to be updated to reference the current Active User from a Helper class.
### Requirement to Fulfill

The Active User will be able to edit or delete products they have added from this particular view.

**Comment by daynewright** [comment]
Does this need to reference the `ActiveUser` singleton instance instead of the Helper class?  Is the Helper class still needed after the singleton was created?
