### ISSUE TITLE
Add Product to Cart User Story

### ISSUE THREAD

**Issue by MattKraatz** [TeamCharles/initial-site#88]
### Feature Description

**Given** a user is on a Product Detail page
**And** the user is not the owner of that Product
**When** the user performs a gesture on the "Add to Cart" link
**Then** the user sees a confirmation message "Added to Cart"
### Requirement to Fulfill

> Refer to the [project requirements](https://github.com/TeamCharles/bangazon-inc/blob/master/projects/INITIAL_BANGAZON_SITE.md#requirements) before filling out this section.

**Comment by MattKraatz** [comment]
@NewEvolution Mr. Manager, how does this user story look for adding a product to an order?
@TeamCharles/team any thoughts?

**Comment by daynewright** [comment]
Looks great to me!
