### ISSUE TITLE
Create ProductTypeController

### ISSUE THREAD

**Issue by daynewright** [TeamCharles/initial-site#9]
### Feature Description

After completed #7 create `ProductTypeController` and update `BangazonContext.cs`.
### Requirement to Fulfill

> Refer to the [project requirements](https://github.com/TeamCharles/bangazon-inc/blob/master/projects/INITIAL_BANGAZON_SITE.md#requirements) before filling out this section.
### Notes

Enable creation of product types via `post`

**Comment by matthamil** [comment]
Resolved with #57
